### ISSUE TITLE
Show GPG signatures in Downloads

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator.github.io#16]

**Comment by overheadhunter** [comment]
Problem is: The website is served via GH Pages and Cloudflare. There is no guarantee, that contents on the download page is not tampered, a MITM could change download link and signature.
Imho we should consider serving the download page over our own server (lets say downloads.cryptomator.org) with a direct, e2e encrypted connection.
Currently code signing is the most effective weapon we have.

**Comment by Coeos3** [comment]
Would be good to get the signature files on the same page as the appimage (linux) file itself. I find it cumbersome to have to go via bintray instead of getting the signature directly on the cryptomator website.
