### ISSUE TITLE
Dedicated Press Kit website

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cryptomator.github.io#2]
Inspired by https://dancounsell.com/articles/a-better-format-for-press-kits

**Comment by MuscleRumble** [comment]
Examples:
https://getslopes.com/press.html
http://www.fintimer.com/press.html

**Comment by tobihagemann** [comment]
Fixed a long time ago, beginning with e7efbda769006b9129a5c6fd6558088545e966d9
