### ISSUE TITLE
Security Without Audit Info Available on the Front Page Affects Overall Trust

### ISSUE THREAD

**Issue by desmonk** [cryptomator/cryptomator.github.io#23]
### Summary

Been a longtime user of program but there has been only one audit so far by cure53.de and that too was not published on their site. I understand that the code is peer reviewed and tested and also fixed many issues. But making an audit report available directly and easily on the front page of the project and on to the website would ensure trust of a user.

### Motivation

Just trying to understand the new world of cryptography.

### Considered Alternatives

Not that I can point out right now.

### Additional Context

Hope this feedback request is taken with utmost care and respect the way the users put their faith in Cryptomator team.

**Comment by tobihagemann** [comment]
Redesigned website has been live for a couple of days. Audit info can be found at https://cryptomator.org/ under "Why is Cryptomator secure and trustworthy?" > "Audited by security researchers", which has a link to https://cryptomator.org/faq/security/audits/.

**Comment by desmonk** [comment]
New design is minimal and modern along with necessary info about the product. Thank you so much guys!
