### ISSUE TITLE
Add GPG Public Key

### ISSUE THREAD

**Issue by faxotherapy** [cryptomator/cryptomator.github.io#25]
Hello,
I can't verify the signature. Only the PGP signature is posted on the download page.

I can run
```
gpg --verify Cryptomator-1.5.1.dmg.asc
```

But if I don't have the public key, having only the PGP signature is useless.
Could you please provide your public key so I can import it.
Thank you.

**Comment by wurstsemmel** [comment]
I agree, please put the link to the public key to the website including fingerprint. That makes the important step of verification of the download much easier. Thank you.

**Comment by lx07** [comment]
It cost me quite some time to get here, it shouldn't be so hard.

**Comment by spbriggs** [comment]
Hi. I notice this issue has been closed but without any details of the resolution. Is the key now published on a trusted website?

**Comment by SailReal** [comment]
While downloading Cryptomator you're redirected to https://cryptomator.org/downloads/linux/thanks/ ... there you can reveal the PGP signature:

![Screenshot from 2020-08-27 20-53-58](https://user-images.githubusercontent.com/1786772/91483113-79de0f80-e8a7-11ea-8ba4-0041590de2ff.png)

**Comment by spbriggs** [comment]
Thanks @SailReal but the question was about validating the signature by comparing the signing key with a known good key. For example, Veracrypt publish the signature of their keys on their website https://www.veracrypt.fr/en/Digital%20Signatures.html (bottom of page). There doesn't seem to be a comparable source of confirmation for Cryptomator.

**Comment by tobihagemann** [comment]
Does that mean that it would help if we add the signature of the public key on our website as well? We could do that.

**Comment by spbriggs** [comment]
Yes, that would help. Although I don't know if this comment still applies : https://github.com/cryptomator/cryptomator.github.io/issues/16#issuecomment-267929725

**Comment by tobihagemann** [comment]
I guess it still applies but added the fingerprint for now. Fun fact: Cryptomator 1.5.8 was signed with a new key.

**Comment by caffeine-1** [comment]
> I guess it still applies but added the fingerprint for now. Fun fact: Cryptomator 1.5.8 was signed with a new key.

Noticed this too, I was waiting for the signature to be posted before running 1.5.8. 1.5.8 is signed with key 615D449FE6E6A235, previous versions were 509C9D6334C80F11. I don't see the new key published anywhere either. 

Guess I'll stay on 1.5.6.

**Comment by gjikia** [comment]
I have the same question: where a new signing key (615D449FE6E6A235) is published??
No traces of the new key are seen on https://gist.github.com/cryptobot/ :-(

**Comment by tobihagemann** [comment]
See this comment, where to find the key: https://github.com/cryptomator/cryptomator.github.io/issues/25#issuecomment-682132067

But I've just uploaded the new key to Cryptobot's gists. :wink:

**Comment by caffeine-1** [comment]
Can you sign the new key with the old key?

**Comment by overheadhunter** [comment]
> Can you sign the new key with the old key?

It is now signed with the old key, however I don't think `gpg --check-sigs` will be able to verify it as the old key is revoked.

**Comment by caffeine-1** [comment]
> > Can you sign the new key with the old key?
> 
> It is now signed with the old key, however I don't think `gpg --check-sigs` will be able to verify it as the old key is revoked.

Thanks! I was able to confirm it on my other machine, it hadn't seen the revocation yet, after --refresh-keys, then the UID changes to [ unknown], but I got it.
