### ISSUE TITLE
On website after successful donation, never got a key

### ISSUE THREAD

**Issue by trentlarson** [cryptomator/cryptomator.github.io#30]
### Description

I donated but never got a key.

### System Setup

* Operating system and version: Firefox on macOS
* Cryptomator version: website
* Drive: FUSE

### Steps to Reproduce

1. Go to https://cryptomator.org/donate/
2. Donate

#### Expected Behavior

It should have given a key.

#### Actual Behavior

It just says "Loading..." in the text box.

#### Reproducibility

Just once.

### Additional Information

<img width="648" alt="Screen Shot 2020-06-13 at 2 44 49 PM" src="https://user-images.githubusercontent.com/238296/84578751-55cd6080-ad85-11ea-91d8-186044240bb2.png">

**Comment by tobihagemann** [comment]
Fixed in 137f507427217a90c27146dc1739b573e754c280
